export const STEP_ONE = [
  {
    id: 1,
    displayName: "Job Title",
    placeHolder: "ex. UX UI Designer",
    type: "text",
    mandatory: true,
    maxLength: null,
    minLength: null,
    objectName: "jobTitle",
    attributes: null,
    authorityCode: "READWRITE",
    row: 1,
    column: 1,
    position: null,
  },
  {
    id: 2,
    displayName: "Company Name",
    placeHolder: "ex. Google",
    type: "text",
    mandatory: true,
    maxLength: null,
    minLength: null,
    objectName: "companyName",
    attributes: null,
    authorityCode: "READWRITE",
    row: 2,
    column: 1,
    position: null,
  },
  {
    id: 3,
    displayName: "Industry",
    placeHolder: "ex. Information Technology",
    type: "text",
    mandatory: true,
    maxLength: null,
    minLength: null,
    objectName: "industry",
    attributes: null,
    authorityCode: "READWRITE",
    row: 3,
    column: 1,
    position: null,
  },
  {
    id: 4,
    displayName: "Location",
    placeHolder: "ex. Chennai",
    type: "text",
    mandatory: false,
    maxLength: null,
    minLength: null,
    objectName: "location",
    attributes: null,
    authorityCode: "READWRITE",
    row: 4,
    column: 1,
    position: null,
  },
  {
    id: 5,
    displayName: "Remote Type",
    placeHolder: "ex. In-Office",
    type: "text",
    mandatory: false,
    maxLength: null,
    minLength: null,
    objectName: "remoteType",
    attributes: null,
    authorityCode: "READWRITE",
    row: 4,
    column: 2,
    position: null,
  },
];

export const STEP_TWO = [
  {
    id: 1,
    displayName: "Experience",
    placeHolder: "Minimum",
    type: "number",
    mandatory: false,
    maxLength: null,
    minLength: null,
    objectName: "experienceMin",
    attributes: null,
    values: null,
    value: null,
    authorityCode: "READWRITE",
    row: 1,
    column: 1,
    position: null,
  },
  {
    id: 2,
    displayName: "",
    placeHolder: "Maximum",
    type: "number",
    mandatory: false,
    maxLength: null,
    minLength: null,
    objectName: "experienceMax",
    values: null,
    value: null,
    attributes: null,
    authorityCode: "READWRITE",
    row: 1,
    column: 2,
    position: null,
  },
  {
    id: 3,
    displayName: "Salary",
    placeHolder: "Minimum",
    type: "number",
    mandatory: false,
    maxLength: null,
    values: null,
    value: null,
    minLength: null,
    objectName: "salaryMin",
    attributes: null,
    authorityCode: "READWRITE",
    row: 2,
    column: 1,
    position: null,
  },
  {
    id: 4,
    displayName: "",
    placeHolder: "Maximum",
    type: "number",
    mandatory: false,
    maxLength: null,
    minLength: null,
    values: null,
    value: null,
    objectName: "salaryMax",
    attributes: null,
    authorityCode: "READWRITE",
    row: 2,
    column: 2,
    position: null,
  },
  {
    id: 5,
    displayName: "Total Employee",
    placeHolder: "ex. 100",
    type: "text",
    mandatory: false,
    maxLength: null,
    minLength: null,
    values: null,
    value: null,
    objectName: "totalEmployee",
    attributes: null,
    authorityCode: "READWRITE",
    row: 3,
    column: 1,
    position: null,
  },
  {
    id: 6,
    displayName: "Apply Type",
    placeHolder: "",
    type: "radio",
    mandatory: false,
    maxLength: null,
    minLength: null,
    values: ["Quick Apply", "External Apply"],
    value: null,
    objectName: "applyType",
    attributes: null,
    authorityCode: "READWRITE",
    row: 4,
    column: 1,
    position: null,
  },
  {
    id: 7,
    displayName: "Work Type",
    placeHolder: "",
    type: "select",
    mandatory: false,
    maxLength: null,
    minLength: null,
    values: ["Full Time", "Part Time"],
    value: null,
    objectName: "workType",
    attributes: null,
    authorityCode: "READWRITE",
    row: 5,
    column: 1,
    position: null,
  },
  {
    id: 8,
    displayName: "Part Time",
    placeHolder: "From",
    type: "time",
    mandatory: true,
    maxLength: null,
    minLength: null,
    values: null,
    value: null,
    objectName: "partTimeFrom",
    attributes: {
      dependentField: "workType",
      whenValueAs: "Part Time",
    },
    authorityCode: "READWRITE",
    row: 6,
    column: 1,
    position: null,
  },
  {
    id: 9,
    displayName: "",
    placeHolder: "To",
    type: "time",
    mandatory: true,
    maxLength: null,
    minLength: null,
    values: null,
    value: null,
    objectName: "partTimeTo",
    attributes: {
      dependentField: "workType",
      whenValueAs: "Part Time",
    },
    authorityCode: "READWRITE",
    row: 6,
    column: 2,
    position: null,
  },
];
